version: '3.8'

services:

  db1:
    image: postgres:latest
    environment:
      POSTGRES_DB: BigCaseClub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - app-volume:/var/lib/postgresql/data-original

  db2:
    image: postgres:latest
    environment:
      POSTGRES_DB: BigCaseClubDepersonalize
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - app-volume:/var/lib/postgresql/data-depersonalize

volumes:
  app-volume: #
