version: '3.8'

services:

  db1:
    image: postgres:latest
    environment:
      POSTGRES_DB: BigCaseClub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - app-volume:/var/lib/postgresql/data-original


volumes:
  app-volume: #
